test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webook_intr"
kafka:
  addr:
    - "localhost:9094"
grpc:
  server:
    #  启动监听 8090 端口
    port: 8090
    etcdAddr: "localhost:12379"
    etcdTTL: 60
migrator:
  http:
    addr: ":8082"
etcd:
  endpoints:
    - "localhost:12379"
