apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
#这里要跟pvc中的name对应上
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"