// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"xiaoweishu/webook/interactive/grpc"
	"xiaoweishu/webook/interactive/repository"
	"xiaoweishu/webook/interactive/repository/cache"
	"xiaoweishu/webook/interactive/repository/dao"
	"xiaoweishu/webook/interactive/service"
)

// Injectors from wire.go:

func InitInteractiveService() *grpc.InteractiveServiceServer {
	db := InitDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	loggerV1 := InitLogger()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitRedis, InitDB,

	InitLogger,
)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
